steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/songlabai-n8n:$BUILD_ID', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/songlabai-n8n:$BUILD_ID']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'songlabai-n8n'
      - '--image'
      - 'gcr.io/$PROJECT_ID/songlabai-n8n:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5678'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--set-env-vars'
      - 'NODE_ENV=production,N8N_PORT=5678,N8N_HOST=0.0.0.0'
      - '--add-cloudsql-instances'
      - 'songlabai-leadgen:us-central1:songlabai-db'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest,GOOGLE_MAPS_API_KEY=google-maps-api-key:latest,CALENDLY_API_KEY=calendly-api-key:latest,SMTP_PASS=smtp-password:latest,N8N_ENCRYPTION_KEY=n8n-encryption-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/songlabai-n8n:$BUILD_ID'